### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by scroniser** [calibreapp/react-live-chat-loader-example-app#1]
Tried to install to add accessibility improvements, but ran into an install error: 
```
Error: Could not find a valid build in the 'H:\chatapp\react-live-chat-loader-example-app\.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\next-server\server\next-server.js:659:23)
    at new Server (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\next-server\server\next-server.js:52:29)
    at createServer (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\server\next.js:2:133)
    at start (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\server\lib\start-server.js:1:323)
    at nextStart (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\cli\next-start.js:22:125)
    at commands.(anonymous function).then.exec (H:\chatapp\react-live-chat-loader-example-app\node_modules\next\dist\bin\next:29:346)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by benschwarz** [comment]
Hey @scroniser, thanks for logging.
What was the command that you ran when you saw this? Have you run next build as the error instructs?

**Comment by scroniser** [comment]
@benschwarz - my fault! I had a typo when I ran next build. I was able to install successfully. Thanks for the prompt reply!
